tap "buo/cask-upgrade"
tap "gcenx/wine"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bottom"
brew "gh"
brew "git"
brew "gotop"
brew "htop"
brew "hugo"
brew "libusb"
brew "mas"
brew "neofetch"
brew "nmap"
brew "screenfetch"
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "appcleaner"
cask "discord"
cask "firefox"
cask "github"
cask "google-japanese-ime"
cask "handbrake"
cask "iina"
cask "maccy"
cask "macdown"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-office"
cask "orion"
cask "raspberry-pi-imager"
cask "steam"
cask "telegram-desktop"
cask "unofficial-wineskin"
cask "visual-studio-code"
cask "vlc"
mas "iMovie", id: 408981434
mas "Infuse", id: 1136220934
mas "LINE", id: 539883307
mas "Microsoft To Do", id: 1274495053
mas "Steam Link", id: 1246969117
mas "Tailscale", id: 1475387142
